apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-user
  labels:
    app: backend-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api-user
  template:
    metadata:
      labels:
        app: backend-api-user
    spec:
      containers:
      - name: backend-api-user
        image: burka9/udagram-api-user:v8
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        envFrom: 
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
          - secretRef:
              name: aws-secret
        ports:
        - containerPort: 8080
      restartPolicy: Always