apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: burka9/udagram-reverseproxy:v8
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always