name: Docker build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    
    - uses: mr-smithers-excellent/docker-build-push@v4
      name: Build and push docker image
      with:
        image: burka9/udagram-api-feed
        registry: docker.io
        directory: udagram-api-feed
        dockerfile: udagram-api-feed/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}